name: Enforce Branch Naming Convention

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

jobs:
  enforce-branch-name:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const prNumber = context.payload.pull_request.number;
            
            console.log(`Validating branch name: ${branchName} for PR #${prNumber}`);

            const regex = /^(feature|fix|refactor|test)\/(IDN|DKN|CHT|FTH|TRN|WLT)-[0-9]+(-[a-z0-9-]+)*$/;

            if (!regex.test(branchName)) {
              const commentBody = `
              ❌ **Invalid Branch Name: \`${branchName}\`**

              Thank you for your contribution! However, the branch name does not follow our required naming convention. 
              This check must pass before the pull request can be merged.

              **Please rename your branch to match the following pattern:**
              \`<type>/<jira-key>-<short-description>\`

              ---
              #### Pattern Breakdown:
              - **type**: One of \`feature\`, \`fix\`, \`refactor\`, \`test\`.
              - **jira-key**: One of \`IDN\`, \`DKN\`, \`CHT\`, \`FTH\`, \`TRN\`, \`WLT\`, followed by a hyphen and the issue number.
              - **short-description**: A short description of the change (e.g., \`add-user-login\`).

              ---
              #### Examples of valid branch names:
              - \`feature/IDN-123-add-user-login\`
              - \`fix/TRN-45-update-payment-gateway\`

              ---
              #### How to fix this:
              1. Go back to your local repository and rename the branch:
                 \`\`\`
                 git branch -m ${branchName} <new-branch-name>
                 \`\`\`
              2. Push the renamed branch to the remote repository. You may need to use force push:
                 \`\`\`
                 git push origin -u <new-bottom-name> --force
                 \`\`\`
              3. Please make a new PR with the updated branch.
              `;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });

              core.setFailed('Branch name does not follow the required naming convention.');
            } else {
              console.log('✅ Branch name is valid.');
            }