spring.application.name=MENA
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER_NAME}
spring.datasource.password=${DATABASE_PASSWORD}
jwt.secret-key=${JWT_SECRET}
server.port=${PORT:8080}


spring.jpa.hibernate.ddl-auto=validate

storage.key=${STORAGE_KEY}
storage.secret=${STORAGE_SECRET}
storage.bucket=${STORAGE_BUCKET}
storage.endpoint=${STORAGE_ENDPOINT}
storage.cdn-endpoint=${STORAGE_CDN_ENDPOINT}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
