spring.application.name=MENA
spring.datasource.url=jdbc:postgresql://localhost:5432/mena
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
JWT_SECRET=qwertyuiopasdfghjklzxcvbnm1234567890QWERTYUIOPASDFGHJKLZXCVBNM0987654321
jwt.secret-key=qwertyuiopasdfghjklzxcvbnm1234567890QWERTYUIOPASDFGHJKLZXCVBNM0987654321
storage.mena.key=STORAGE_MENA_KEY
storage.mena.secret=STORAGE_MENA_SECRET
storage.mena.endpoint=https://digitaloceanspaces.com
storage.mena.bucket=mena-storage
storage.mena.cdn-endpoint=https://mena-dukan

storage.dukan.key=STORAGE_DUKAN_KEY
storage.dukan.secret=STORAGE_DUKAN_SECRET
storage.dukan.endpoint=https://digitaloceanspaces.com
storage.dukan.bucket=mena-dukan
storage.dukan.cdn-endpoint=https://mena-dukan

storage.trends.key=STORAGE_TRENDS_KEY
storage.trends.secret=STORAGE_TRENDS_SECRET
storage.trends.endpoint=https://digitaloceanspaces.com
storage.trends.bucket=mena-trends
storage.trends.cdn-endpoint=https://mena-trends

storage.wallet.key=STORAGE_WALLET_KEY
storage.wallet.secret=STORAGE_WALLET_SECRET
storage.wallet.endpoint=https://digitaloceanspaces.com
storage.wallet.bucket=mena-wallet
storage.wallet.cdn-endpoint=https://mena-wallet

storage.faith.key=STORAGE_FAITH_KEY
storage.faith.secret=STORAGE_FAITH_SECRET
storage.faith.endpoint=https://digitaloceanspaces.com
storage.faith.bucket=mena-faith
storage.faith.cdn-endpoint=https://mena-faith

# Multipart file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
file-size.modules.dukan=5
file-size.modules.trends=100
file-size.modules.identity=5
file-size.modules.faith=5
file-size.modules.chat=5
