identity-rate-limit.endpoints[/identity/authentication/login].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/login].short-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/login].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/login].long-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/login].block-duration-seconds=900
identity-rate-limit.endpoints[/identity/authentication/refresh].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/refresh].short-term-window-seconds=900
identity-rate-limit.endpoints[/identity/authentication/refresh].long-term-attempts-limit=10
identity-rate-limit.endpoints[/identity/authentication/refresh].long-term-window-seconds=3600
identity-rate-limit.endpoints[/identity/authentication/refresh].block-duration-seconds=900
identity-rate-limit.endpoints[/identity/authentication/request-reset-password-otp].short-term-attempts-limit=1
identity-rate-limit.endpoints[/identity/authentication/request-reset-password-otp].short-term-window-seconds=60
identity-rate-limit.endpoints[/identity/authentication/request-reset-password-otp].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/request-reset-password-otp].long-term-window-seconds=600
identity-rate-limit.endpoints[/identity/authentication/request-reset-password-otp].block-duration-seconds=900
identity-rate-limit.endpoints[/identity/authentication/verify-reset-password-otp].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/verify-reset-password-otp].short-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/verify-reset-password-otp].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/verify-reset-password-otp].long-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/verify-reset-password-otp].block-duration-seconds=300
identity-rate-limit.endpoints[/identity/authentication/reset-password].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/reset-password].short-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/reset-password].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/reset-password].long-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/reset-password].block-duration-seconds=300
identity-rate-limit.endpoints[/identity/authentication/register/request-otp].short-term-attempts-limit=1
identity-rate-limit.endpoints[/identity/authentication/register/request-otp].short-term-window-seconds=60
identity-rate-limit.endpoints[/identity/authentication/register/request-otp].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/register/request-otp].long-term-window-seconds=600
identity-rate-limit.endpoints[/identity/authentication/register/request-otp].block-duration-seconds=900
identity-rate-limit.endpoints[/identity/authentication/register/verify-otp].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/register/verify-otp].short-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/register/verify-otp].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/register/verify-otp].long-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/register/verify-otp].block-duration-seconds=300
identity-rate-limit.endpoints[/identity/authentication/register].short-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/register].short-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/register].long-term-attempts-limit=5
identity-rate-limit.endpoints[/identity/authentication/register].long-term-window-seconds=120
identity-rate-limit.endpoints[/identity/authentication/register].block-duration-seconds=300